"""Initial migration

Revision ID: c1a2b9e18684
Revises: 
Create Date: 2026-01-08 18:06:41.943762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a2b9e18684'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referee_id', sa.UUID(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('successful_at', sa.DateTime(), nullable=True),
    sa.Column('reward_granted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id')
    )
    op.create_index(op.f('ix_referral_id'), 'referral', ['id'], unique=False)
    op.create_index(op.f('ix_referral_referrer_id'), 'referral', ['referrer_id'], unique=False)
    op.create_table('transactionledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_transaction_id', sa.String(), nullable=True),
    sa.Column('credits_added_regular', sa.Integer(), nullable=True),
    sa.Column('credits_added_hq', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionledger_id'), 'transactionledger', ['id'], unique=False)
    op.create_index(op.f('ix_transactionledger_provider_transaction_id'), 'transactionledger', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactionledger_user_id'), 'transactionledger', ['user_id'], unique=False)
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('referred_by_id', sa.UUID(), nullable=True),
    sa.Column('credits_regular', sa.Integer(), nullable=True),
    sa.Column('credits_hq', sa.Integer(), nullable=True),
    sa.Column('storage_limit', sa.Integer(), nullable=True),
    sa.Column('storage_used', sa.Integer(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_userprofile_id'), 'userprofile', ['id'], unique=False)
    op.create_index(op.f('ix_userprofile_referral_code'), 'userprofile', ['referral_code'], unique=True)
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('replicate_job_id', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_index(op.f('ix_userprofile_referral_code'), table_name='userprofile')
    op.drop_index(op.f('ix_userprofile_id'), table_name='userprofile')
    op.drop_table('userprofile')
    op.drop_index(op.f('ix_transactionledger_user_id'), table_name='transactionledger')
    op.drop_index(op.f('ix_transactionledger_provider_transaction_id'), table_name='transactionledger')
    op.drop_index(op.f('ix_transactionledger_id'), table_name='transactionledger')
    op.drop_table('transactionledger')
    op.drop_index(op.f('ix_referral_referrer_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_id'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
